# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1f\n\rStreamRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"!\n\x0eStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb4\x02\n\x10MessagingService\x12@\n\x0bSendMessage\x12\x17.example.MessageRequest\x1a\x18.example.MessageResponse\x12\x43\n\x0eStreamMessages\x12\x16.example.StreamRequest\x1a\x17.example.StreamResponse0\x01\x12K\n\x14StreamClientMessages\x12\x17.example.MessageRequest\x1a\x18.example.MessageResponse(\x01\x12L\n\x13\x42idirectionalStream\x12\x17.example.MessageRequest\x1a\x18.example.MessageResponse(\x01\x30\x01\x42\x08Z\x06./grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./grpc'
  _globals['_MESSAGEREQUEST']._serialized_start=26
  _globals['_MESSAGEREQUEST']._serialized_end=59
  _globals['_MESSAGERESPONSE']._serialized_start=61
  _globals['_MESSAGERESPONSE']._serialized_end=96
  _globals['_STREAMREQUEST']._serialized_start=98
  _globals['_STREAMREQUEST']._serialized_end=129
  _globals['_STREAMRESPONSE']._serialized_start=131
  _globals['_STREAMRESPONSE']._serialized_end=164
  _globals['_MESSAGINGSERVICE']._serialized_start=167
  _globals['_MESSAGINGSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
